#!/usr/bin/env python3
"""Recheck of Hard-Zeta Phase II Round A-U.2d.3 (source item 47).

數學戰士「墜衡」 / AMRAL Research Lab.
Subject: Neo.K + Aletheia, *Second-Order Survival Closure via Explicit Diophantine
Duration, Continued-Fraction Height Capacity, and Sparse-or-Congested B-Renewal*
(v0.1, 2026-08-13). Ships a verification script, a constants JSON, and literature
notes.

## What is exactly checkable here, and it is more than usual

The round takes one conservative external exponent, `rho_star = 4.1164`, and
derives everything else from it. That number is a **terminating decimal**, so

    mu_star = rho_star + 1 = 12791/2500
    theta_star = 1/mu_star = 2500/12791
    sigma_star = 1/(1 + theta_star) = 12791/15291
    1 - sigma_star = 2500/15291

are **exact rationals**, and the shipped JSON publishes 100 digits of each. Same
situation as `U_beta(L)` in RUN-027: a quantity the artifact computes in floating
point that is in fact rational, so the published digits can be checked against an
exact expansion rather than against a better approximation.

## And two coefficients that can be wrong in a way constants cannot

Sections 9 and 16 do not just quote constants, they quote **second-order
coefficients of asymptotic expansions**:

    q+ >= c0 * y/q + c1 * y/q^(3/2) - q            (section 9)
    q  >= A/eta + (kappa/eta^(3/2)) * sqrt(A)      (section 16)

A wrong first coefficient is loud. A wrong *second* coefficient is quiet: the
expansion still looks right and still tracks the true value to leading order. The
discriminating test is the scaled residual, which tends to zero exactly when the
coefficient is right and to a nonzero constant when it is not. That is what this
file measures, rather than checking the constants and calling the expansion
verified.

## The continued fraction, computed without floating point at all

The artifact's convergents come from mpmath's floor-and-reciprocal loop at 100
digits. They are recomputed here by an integer-only recursion: every step of the
continued fraction of `log_2 3` is `floor(log_u v)` for exact rationals `u, v` in
the multiplicative group generated by 2 and 3, so each partial quotient is decided
by comparing `2^A` against `3^B`. No logarithm is evaluated.

That certification is **not free and does not go all the way**: the integers grow
with the convergent denominators, so the run reports the largest denominator it
actually certified rather than claiming the whole table. Rows past that boundary
are cross-checked at four times the artifact's precision and reported separately.
A bound is not a measurement, and a cutoff silently crossed is worse than one
named.

## Artifacts

Standing rule since item 35: recompute independently, never re-run the shipped
script, and check whether the shipped JSON is what that script would produce.
Items 35, 45 and 46 all failed that check.

Usage:  python code/src47_survival_closure.py --bundle DIR [--cf-budget SECONDS]
"""

from __future__ import annotations

import argparse
import json
import pathlib
import random
import re
import sys
import time
from fractions import Fraction

import mpmath as mp

HERE = pathlib.Path(__file__).resolve().parent

WORKING_DPS = 400          # the artifact runs at 100; this is four times that
REPORT_DPS = 120

#: What Fan-Queffelec-Queffelec (arXiv:2303.06850) report for alpha = log2/log3,
#: attributed there to Wang and Wu and improving Rhin's 7.616. The round says it
#: uses this "conservatively"; a larger exponent is the weaker assumption, so the
#: claim is `rho_star > this`, and it is an exact comparison of two terminating
#: decimals rather than something to take on trust.
CITED_EXPONENT = "4.11633052"
RHIN_EXPONENT = "7.616"

CONSTANTS_JSON = "Hard_Zeta_AU2d3_survival_closure_constants.json"
VERIFY_SCRIPT = "verify_Hard_Zeta_AU2d3_survival_closure.py"
ROUND_DOC = "Hard_Zeta_Phase_II_Round_AU2d3_Second_Order_Survival_Closure_v0.1.md"


# ---------------------------------------------------------------------------
# exact decimal expansion of a rational, and a correctly-rounded comparison
# ---------------------------------------------------------------------------

def rational_digits(value: Fraction, places: int) -> str:
    """Exact decimal expansion, truncated to `places` digits after the point."""
    sign = "-" if value < 0 else ""
    value = abs(value)
    whole = value.numerator // value.denominator
    rest = value - whole
    num, den = rest.numerator, rest.denominator
    out = []
    for _ in range(places):
        num *= 10
        digit, num = divmod(num, den)
        out.append(str(digit))
    return "%s%d.%s" % (sign, whole, "".join(out))


def leading_agreement(published: str, reference: str) -> int:
    """How many characters of `published` a longer `reference` agrees with."""
    n = 0
    for a, b in zip(published, reference):
        if a != b:
            break
        n += 1
    return n


def decimals_published(text: str) -> int:
    return len(text.split(".")[1]) if "." in text else 0


def decimal_verdict(published: str, reference: str) -> dict:
    """Is a published decimal exact, its correct rounding, or actually wrong?

    ONE implementation, because the distinction is easy to get wrong in the
    ACCUSING direction and getting it wrong twice is how a run publishes a
    finding against correct arithmetic. Two ways to get it wrong, both met here
    while writing this file:

      * comparing against a TRUNCATION calls a correctly-rounded last digit an
        error;
      * checking the reference digit AT the last published position instead of
        the one AFTER it misses the carry -- `...173219729` correctly rounds to
        `...17322`, and reading the `1` rather than the `9` calls that wrong.

    So round once, properly, with exact rational arithmetic, and compare.
    `reference` must be a decimal string with strictly more digits than
    `published`, from a computation far more precise than the artifact's.
    """
    places = decimals_published(published)
    ref = Fraction(reference)
    scale = 10 ** places
    truncated = Fraction(int(ref * scale), scale)
    remainder = ref * scale - int(ref * scale)
    rounded = truncated + (Fraction(1, scale) if remainder >= Fraction(1, 2)
                           else Fraction(0))
    shown = Fraction(published)
    if shown == truncated == rounded:
        return {"published_decimals": places, "digits_correct": places,
                "verdict": "exact to every published digit"}
    if shown == rounded:
        return {"published_decimals": places, "digits_correct": places,
                "verdict": "correctly rounded at the last digit"}
    if shown == truncated:
        return {"published_decimals": places, "digits_correct": places,
                "verdict": "truncated rather than rounded at the last digit"}
    agree = leading_agreement(published, reference)
    correct = max(0, agree - (published.index(".") + 1))
    return {"published_decimals": places, "digits_correct": correct,
            "verdict": "OVER-PUBLISHED",
            "digits_beyond_the_computation": places - correct,
            "published_tail": published[-16:],
            "reference_tail": reference[max(0, len(published) - 16):len(published) + 4]}


def rational_verdict(published: str, exact: Fraction) -> dict:
    """Same comparison, but the verdict for a RATIONAL cannot be over-publication.

    A transcendental printed past its working precision has an excuse. A
    quantity that is exactly `2500/12791` has none: every digit is available, so
    a mismatch beyond the last-digit rounding is simply wrong. Until this
    distinction was drawn, `wrong_digits` was a list the gate reported and gated
    on that no input could ever fill.
    """
    places = decimals_published(published)
    verdict = decimal_verdict(published, rational_digits(exact, places + 12))
    if verdict["verdict"] == "OVER-PUBLISHED":
        verdict["verdict"] = "WRONG"
        verdict.pop("digits_beyond_the_computation", None)
    return verdict


def mpf_verdict(published: str, value) -> dict:
    places = decimals_published(published)
    with mp.workdps(WORKING_DPS):
        integer_digits = len(mp.nstr(value, 5).split(".")[0].lstrip("-"))
        if abs(value) < 1:
            integer_digits = 0
        reference = mp.nstr(value, places + integer_digits + 12, strip_zeros=False)
    if "." not in reference:                                # pragma: no cover
        reference += ".0"
    if len(reference.split(".")[1]) <= places:              # pragma: no cover
        reference = mp.nstr(value, places + integer_digits + 20, strip_zeros=False)
    return decimal_verdict(published, reference)


# ---------------------------------------------------------------------------
# section 1 — the exponent chain, exactly
# ---------------------------------------------------------------------------

def check_exponent_chain(data: dict) -> dict:
    rho = Fraction(data["rho_star"])
    mu = rho + 1
    theta = 1 / mu
    sigma = 1 / (1 + theta)
    congestion = 1 - sigma

    identities = {
        "mu_star == rho_star + 1": Fraction(data["mu_star"]) == mu,
        "theta_star * mu_star == 1": theta * mu == 1,
        "sigma_star * (1 + theta_star) == 1": sigma * (1 + theta) == 1,
        "sigma_star + congestion == 1": sigma + congestion == 1,
        "rho_star is conservative against the cited exponent":
            rho > Fraction(CITED_EXPONENT),
        "the cited exponent improves on Rhin's":
            Fraction(CITED_EXPONENT) < Fraction(RHIN_EXPONENT),
        "theta_star < 1": theta < 1,
        "sigma_star < 1": sigma < 1,
        "congestion > 0": congestion > 0,
    }
    published = {
        "theta_star": (data["theta_star"], theta),
        "sigma_star": (data["sigma_star"], sigma),
        "congestion_exponent": (data["congestion_exponent"], congestion),
    }
    verdicts = {k: rational_verdict(text, exact) for k, (text, exact) in published.items()}
    return {
        "rho_star_as_an_exact_rational": "%d/%d" % (rho.numerator, rho.denominator),
        "cited_exponent": CITED_EXPONENT,
        "rho_star_minus_cited": str(rho - Fraction(CITED_EXPONENT)),
        "theta_star_exact": "%d/%d" % (theta.numerator, theta.denominator),
        "sigma_star_exact": "%d/%d" % (sigma.numerator, sigma.denominator),
        "congestion_exact": "%d/%d" % (congestion.numerator, congestion.denominator),
        "identities": identities,
        "published_digits": verdicts,
        "all_identities_hold": all(identities.values()),
        "wrong_digits": sorted(k for k, v in verdicts.items() if v["verdict"] == "WRONG"),
    }


# ---------------------------------------------------------------------------
# section 2 — the transcendental constants, against their closed forms
# ---------------------------------------------------------------------------

def check_transcendental_constants(data: dict, doc: str) -> dict:
    with mp.workdps(WORKING_DPS):
        ln2 = mp.log(2)
        eta = 1 / (6 * ln2)
        kappa = 1 / (12 * mp.sqrt(2))
        closed = {
            "eta_beta": (eta, "1/(6 ln 2)"),
            "kappa_rot": (kappa, "1/(12 sqrt 2)"),
            "cf_leading_constant": (6 * ln2 ** 2, "6 (ln 2)^2 = ln2/eta"),
            "cf_second_order_constant": (3 * ln2 ** 3 / mp.sqrt(2),
                                         "3 (ln 2)^3 / sqrt 2 = ln2 kappa/eta^2"),
        }
        verdicts = {k: mpf_verdict(data[k], v) for k, (v, _) in closed.items()}

        # the identities the round's own algebra requires between them
        rel = {
            "cf_leading == ln2/eta": abs(6 * ln2 ** 2 - ln2 / eta),
            "cf_second == ln2*kappa/eta^2": abs(3 * ln2 ** 3 / mp.sqrt(2) - ln2 * kappa / eta ** 2),
            "cf_second/cf_leading == kappa/eta":
                abs((3 * ln2 ** 3 / mp.sqrt(2)) / (6 * ln2 ** 2) - kappa / eta),
            "1/eta == 6 ln 2": abs(1 / eta - 6 * ln2),
        }
        tolerance = mp.mpf(10) ** (-(WORKING_DPS - 20))
        relations = {k: bool(v < tolerance) for k, v in rel.items()}

        # constants that appear only in the round document, never in the JSON
        doc_only = {
            "1/eta_beta = 6 ln 2": (1 / eta, "4.158883083360"),
            "kappa_rot/eta_beta^(3/2)": (kappa / eta ** mp.mpf("1.5"), "0.499768435370"),
            "ln2/eta_beta": (ln2 / eta, "2.882718083509"),
            "ln2*kappa_rot/eta_beta^2": (ln2 * kappa / eta ** 2, "0.706451969171"),
            "kappa_rot": (kappa, "0.05892556509888"),
            "eta_beta": (eta, "0.24044917348149"),
        }
        doc_rows, doc_bad = {}, []
        for name, (value, printed) in doc_only.items():
            places = decimals_published(printed)
            with mp.workdps(WORKING_DPS):
                nearest = mp.nstr(value, places + len(printed.split(".")[0]),
                                  strip_zeros=False)
            ok = nearest[:len(printed)] == printed
            if not ok:                       # allow a correctly rounded last digit
                ok = abs(mp.mpf(printed) - value) <= mp.mpf(10) ** (-places) / 2
            doc_rows[name] = {"document_prints": printed, "agrees": bool(ok)}
            if not ok:
                doc_bad.append(name)
            if printed not in doc:
                doc_rows[name]["_not_found_in_document"] = True

    return {
        "closed_forms": {k: v[1] for k, v in closed.items()},
        "published_digits": verdicts,
        "relations_between_them": relations,
        "constants_printed_only_in_the_round_document": doc_rows,
        "over_published": sorted(k for k, v in verdicts.items()
                                 if v["verdict"] == "OVER-PUBLISHED"),
        # A trailing digit or two is over-publication. A constant that parts
        # company with its closed form in the first twenty digits is a different
        # number, and calling that "over-published" would file a wrong constant
        # under a rounding complaint.
        "disagreeing_beyond_rounding": sorted(
            k for k, v in verdicts.items()
            if v.get("digits_beyond_the_computation", 0) > 20),
        "all_relations_hold": all(relations.values()),
        "document_constants_disagreeing": doc_bad,
    }


# ---------------------------------------------------------------------------
# section 3 — the continued fraction of log_2 3, by integers only
# ---------------------------------------------------------------------------

#: How many integer comparisons the certified route actually performed. Without
#: this the claim "no floating point is evaluated" is unfalsifiable from the
#: report: swapping the integer route for the mpmath one produces the SAME
#: partial quotients, so every other field agrees and the two-method agreement
#: check confirms a comparison of a thing with itself.
_COMPARISONS = {"count": 0}


def _cmp_pow(a2: int, a3: int) -> int:
    """Sign of 2^a2 * 3^a3 - 1, for integer exponents of either sign."""
    _COMPARISONS["count"] += 1
    if a2 >= 0 and a3 >= 0:
        return 0 if (a2 == 0 and a3 == 0) else 1
    if a2 <= 0 and a3 <= 0:
        return 0 if (a2 == 0 and a3 == 0) else -1
    if a2 > 0:                       # compare 2^a2 against 3^(-a3)
        left, right = 1 << a2, 3 ** (-a3)
    else:                            # compare 3^a3 against 2^(-a2)
        left, right = 3 ** a3, 1 << (-a2)
    return (left > right) - (left < right)


def cmp_pow_self_test() -> dict:
    """The primitive everything else rests on, on cases decided by hand.

    2^19 = 524288 < 531441 = 3^12 is the classic near-miss that makes 19/12 a
    convergent of log_2 3; 2^8 = 256 > 243 = 3^5 is the other side.
    """
    cases = [
        ("2^19 < 3^12", (19, -12), -1),
        ("2^8 > 3^5", (8, -5), 1),
        ("2^1 < 3^1", (1, -1), -1),
        ("2^2 > 3^1", (2, -1), 1),
        ("2^0 * 3^0 == 1", (0, 0), 0),
        ("2^-1 < 1", (-1, 0), -1),
        ("3^1 > 1", (0, 1), 1),
    ]
    rows = {name: _cmp_pow(*args) == want for name, args, want in cases}
    return {"cases": rows, "all_correct": all(rows.values())}


def exact_continued_fraction(max_terms: int, budget_seconds: float) -> dict:
    """Partial quotients of log_2 3, decided by integer comparisons only.

    State is `log_u v` with u, v = 2^a 3^b, so `floor(log_u v)` is the largest k
    with `u^k <= v`, i.e. a comparison of two integer powers. No logarithm and no
    floating point is evaluated anywhere in this function.
    """
    u = (1, 0)          # u = 2
    v = (0, 1)          # v = 3
    terms, started, stopped = [], time.time(), None
    for _ in range(max_terms):
        if time.time() - started > budget_seconds:
            stopped = "time budget"
            break
        # Largest k with u^k <= v, by doubling then bisection. Incrementing k
        # one at a time cost 56 comparisons for the partial quotient 55, each on
        # ten-million-bit integers; this costs about twelve. The budget still
        # binds inside the search, because one comparison at this size is not
        # cheap either.
        def fits(k: int) -> bool:
            return _cmp_pow(k * u[0] - v[0], k * u[1] - v[1]) <= 0

        hi = 1
        while True:
            if time.time() - started > budget_seconds:
                stopped = "time budget, mid-partial-quotient"
                break
            if not fits(hi):
                break
            hi *= 2
            if hi > 10 ** 7:                         # pragma: no cover
                stopped = "runaway partial quotient"
                break
        if stopped:
            break
        low = hi // 2                                # fits(low) is known true
        while hi - low > 1:
            if time.time() - started > budget_seconds:
                stopped = "time budget, mid-partial-quotient"
                break
            mid = (low + hi) // 2
            if fits(mid):
                low = mid
            else:
                hi = mid
        if stopped:
            break
        k = low
        terms.append(k)
        u, v = (v[0] - k * u[0], v[1] - k * u[1]), u
        if u == (0, 0):                              # pragma: no cover
            stopped = "terminated"
            break
    return {"terms": terms, "stopped_because": stopped or "reached max_terms",
            "seconds": round(time.time() - started, 2),
            "integer_comparisons": _COMPARISONS["count"]}


def convergents_from_terms(terms: list[int]) -> list[tuple[int, int, int]]:
    """(index, p, q) for each convergent of the given partial quotients."""
    p_prev, p_cur = 0, 1
    q_prev, q_cur = 1, 0
    out = []
    for i, a in enumerate(terms):
        p_prev, p_cur = p_cur, a * p_cur + p_prev
        q_prev, q_cur = q_cur, a * q_cur + q_prev
        out.append((i, p_cur, q_cur))
    return out


def mpmath_continued_fraction(count: int) -> list[int]:
    """The same sequence at four times the artifact's precision. Independent
    only in arithmetic, not in method -- which is why the integer route above
    exists and is the one that certifies."""
    with mp.workdps(WORKING_DPS):
        x = mp.log(3, 2)
        terms = []
        for _ in range(count):
            a = int(mp.floor(x))
            terms.append(a)
            frac = x - a
            if frac == 0:                            # pragma: no cover
                break
            x = 1 / frac
    return terms


def check_continued_fraction(data: dict, budget: float) -> dict:
    rows = data["upper_convergent_diagnostics"]
    primitive = cmp_pow_self_test()
    before = _COMPARISONS["count"]
    exact = exact_continued_fraction(max_terms=26, budget_seconds=budget)
    certified_terms = exact["terms"]
    high = mpmath_continued_fraction(len(certified_terms) + 8)

    agree_upto = 0
    for a, b in zip(certified_terms, high):
        if a != b:
            break
        agree_upto += 1

    conv_exact = convergents_from_terms(certified_terms)
    conv_high = convergents_from_terms(high)
    by_index_exact = {i: (p, q) for i, p, q in conv_exact}
    by_index_high = {i: (p, q) for i, p, q in conv_high}

    largest_certified_q = max((q for _, _, q in conv_exact), default=0)

    row_checks, disagreements = [], []
    for row in rows:
        idx = row["index"]
        source = "integer-certified" if idx + 1 < len(certified_terms) else "400 dps"
        table = by_index_exact if source == "integer-certified" else by_index_high
        got = table.get(idx)
        nxt = table.get(idx + 1)
        ok = (got is not None and nxt is not None
              and got == (row["p"], row["q"])
              and nxt[1] == row["q_next"]
              and (certified_terms if source == "integer-certified" else high)[idx]
              == row["partial_quotient"]
              and (certified_terms if source == "integer-certified" else high)[idx + 1]
              == row["next_partial_quotient"])
        row_checks.append({"index": idx, "q": row["q"], "decided_by": source,
                           "agrees": bool(ok)})
        if not ok:
            disagreements.append({"index": idx, "shipped": [row["p"], row["q"],
                                                            row["q_next"]],
                                  "recomputed": [got, nxt]})

    return {
        "cmp_pow_self_test": primitive,
        "integer_comparisons_performed": exact["integer_comparisons"] - before,
        "terms_certified_by_integer_comparison": len(certified_terms),
        "largest_denominator_certified": largest_certified_q,
        "certification_stopped_because": exact["stopped_because"],
        "certification_seconds": exact["seconds"],
        "certified_partial_quotients": certified_terms,
        "the_two_methods_agree_on_the_first_n_terms": agree_upto,
        "the_two_methods_agree_everywhere_both_ran": agree_upto == len(certified_terms),
        "rows": row_checks,
        "rows_integer_certified": sum(1 for r in row_checks
                                      if r["decided_by"] == "integer-certified"),
        "rows_cross_checked_only": sum(1 for r in row_checks
                                       if r["decided_by"] != "integer-certified"),
        "disagreements": disagreements,
    }


# ---------------------------------------------------------------------------
# section 4 — the continued-fraction tax, and the upper-convergent filter
# ---------------------------------------------------------------------------

def beta_enclosure(terms: list[int], want: int) -> tuple[Fraction, Fraction]:
    """An exact rational bracket for log_2 3 from certified partial quotients."""
    conv = convergents_from_terms(terms)
    pick = [c for c in conv if c[0] >= want][-2:] or conv[-2:]
    (i1, p1, q1), (i2, p2, q2) = pick[-2], pick[-1]
    lo, hi = Fraction(p1, q1), Fraction(p2, q2)
    return (lo, hi) if lo < hi else (hi, lo)


def check_cf_tax(data: dict, cf: dict) -> dict:
    """1/(q+q+) < p - beta q < 1/q+ on every shipped upper convergent.

    Decided as a comparison of exact rationals wherever the bracket certifies it,
    and reported as undecided rather than rounded when it does not.
    """
    terms = cf["certified_partial_quotients"]
    lo, hi = beta_enclosure(terms, want=len(terms) - 2)
    rows, undecided, violations = [], [], []
    for row in data["upper_convergent_diagnostics"]:
        p, q, qn = row["p"], row["q"], row["q_next"]
        err_lo, err_hi = p - hi * q, p - lo * q          # exact interval for p-beta*q
        lower, upper = Fraction(1, q + qn), Fraction(1, qn)
        decided_lower = err_lo > lower or err_hi <= lower
        decided_upper = err_hi < upper or err_lo >= upper
        holds_lower = err_lo > lower
        holds_upper = err_hi < upper
        positive = err_lo > 0
        entry = {"index": row["index"], "q": q,
                 "lower_bound_decided": bool(decided_lower),
                 "upper_bound_decided": bool(decided_upper),
                 "1/(q+q+) < p-beta q": bool(holds_lower) if decided_lower else None,
                 "p-beta q < 1/q+": bool(holds_upper) if decided_upper else None,
                 "p/q is above beta": bool(positive) if (err_lo > 0 or err_hi < 0) else None}
        rows.append(entry)
        if not (decided_lower and decided_upper):
            undecided.append(row["index"])
        else:
            if not holds_lower or not holds_upper:
                violations.append(entry)
    # The rows the exact bracket cannot judge are not left silent. They are
    # decided at four times the artifact's precision and reported SEPARATELY,
    # because "checked exactly" and "checked well" are different claims.
    with mp.workdps(WORKING_DPS):
        beta = mp.log(3, 2)
        hp_violations = []
        for row in data["upper_convergent_diagnostics"]:
            p, q, qn = row["p"], row["q"], row["q_next"]
            err = mp.mpf(p) - beta * q
            if not (mp.mpf(1) / (q + qn) < err < mp.mpf(1) / qn):
                hp_violations.append(row["index"])
    return {
        "beta_bracket_width": mp.nstr(mp.mpf(float(hi - lo)), 4),
        "rows": rows,
        "rows_decided_exactly": sum(1 for r in rows
                                    if r["lower_bound_decided"] and r["upper_bound_decided"]),
        "rows_the_exact_bracket_cannot_judge": undecided,
        "violations": violations,
        "violations_at_400_dps_over_every_row": hp_violations,
        "every_row_holds_by_one_route_or_the_other":
            not violations and not hp_violations,
    }


def check_upper_filter(data: dict, cf: dict) -> dict:
    """The script keeps rows with `err > 0`. Check BOTH directions.

    A filter is only verified when the things it dropped are checked too --
    otherwise one that silently drops half the valid rows still passes.

    Which side of beta a convergent falls on is decided by PARITY, not by the
    numeric bracket: convergents alternate, so with `a_0 = 1 < beta` the odd
    indices lie above. A first version asked the bracket instead and reported
    index 13 as undecided -- because the bracket is built FROM convergents 13
    and 14, so its width is exactly the quantity it was being asked to resolve.
    A test that cannot decide its own last case is measuring its own input. The
    parity rule gives the verdict; the bracket now only CONFIRMS it, wherever it
    is tight enough to have an opinion.
    """
    terms = cf["certified_partial_quotients"]
    lo, hi = beta_enclosure(terms, want=len(terms) - 2)
    kept = {row["index"] for row in data["upper_convergent_diagnostics"]}
    conv = convergents_from_terms(terms)

    above = [i for i, _, _ in conv[:-1] if i % 2 == 1]
    below = [i for i, _, _ in conv[:-1] if i % 2 == 0]

    confirmed, contradicted, silent = 0, [], 0
    for i, p, q in conv[:-1]:
        err_lo, err_hi = p - hi * q, p - lo * q
        if err_lo > 0:
            side = "above"
        elif err_hi < 0:
            side = "below"
        else:
            silent += 1
            continue
        if (side == "above") != (i % 2 == 1):
            contradicted.append(i)
        else:
            confirmed += 1

    limit = max(kept)
    expected = [i for i in above if i <= limit]
    wrongly_dropped = sorted(set(expected) - kept)
    wrongly_kept = sorted(i for i in kept if i in set(below))
    return {
        "side_decided_by": "parity of the convergent index",
        "indices_above_beta_up_to_the_last_shipped_row": expected,
        "indices_below_beta": [i for i in below if i <= limit],
        "shipped_indices": sorted(kept),
        "above_beta_but_missing_from_the_JSON": wrongly_dropped,
        "below_beta_but_present_in_the_JSON": wrongly_kept,
        "parity_confirmed_by_the_exact_bracket_on": confirmed,
        "parity_contradicted_by_the_exact_bracket_on": contradicted,
        "indices_the_bracket_is_too_wide_to_judge": silent,
        "the_filter_is_right_in_both_directions":
            not wrongly_dropped and not wrongly_kept and not contradicted,
    }


# ---------------------------------------------------------------------------
# section 5 — the shipped per-row capacities
# ---------------------------------------------------------------------------

def significant_digits(published: str, reference: str) -> tuple[int, int]:
    """(published, correct) counted in SIGNIFICANT digits, not decimal places.

    `p - beta*q` is around `1e-10` for the large convergents, so a tenth of the
    string is leading zeros. Counting decimals there would flatter the artifact
    on the small rows and punish it on the large ones.
    """
    lead = published.index(".") + 1
    zeros = len(published[lead:]) - len(published[lead:].lstrip("0"))
    shown = len(published) - lead - zeros
    correct = max(0, leading_agreement(published, reference) - lead - zeros)
    return shown, min(correct, shown)


def check_row_arithmetic(data: dict) -> dict:
    """Recompute every published row field, and PREDICT where precision runs out.

    "Over-published" on its own is a label. The useful form is a number a reader
    can re-derive: mpmath keeps about `dps` significant digits, so subtracting
    two quantities of size `beta*q` to get one of size `1/q+` costs about
    `log10(beta * q * q+)` of them. That prediction is checked against the
    measured agreement here, so the finding carries its own mechanism instead of
    an adjective.
    """
    with mp.workdps(WORKING_DPS):
        ln2 = mp.log(2)
        eta = 1 / (6 * ln2)
        kappa = 1 / (12 * mp.sqrt(2))
        beta = mp.log(3, 2)
        rows, worst, mispredicted = [], None, []
        for row in data["upper_convergent_diagnostics"]:
            q_i, qn_i, p_i = row["q"], row["q_next"], row["p"]
            q, qn, pv = mp.mpf(q_i), mp.mpf(qn_i), mp.mpf(p_i)
            first = (q + qn) * (eta * q + mp.mpf(1) / 3) / ln2
            bracket = eta * q + mp.mpf(1) / 3 - kappa * mp.sqrt(q)
            second = (q + qn) * bracket / ln2 if bracket > 0 else mp.mpf(0)
            err = pv - beta * q

            fields = {
                "first_order_height_capacity": first,
                "second_order_height_capacity_diagnostic": second,
                "primitive_error": err,
            }
            verdicts, shown_correct = {}, {}
            for name, value in fields.items():
                published = row[name]
                verdicts[name] = mpf_verdict(published, value)["verdict"]
                places = decimals_published(published)
                integer_digits = 0 if abs(value) < 1 else len(
                    mp.nstr(value, 5).split(".")[0].lstrip("-"))
                reference = mp.nstr(value, places + integer_digits + 12,
                                    strip_zeros=False)
                shown_correct[name] = significant_digits(published, reference)

            shown, correct = shown_correct["primitive_error"]
            predicted = shown - float(mp.log(beta * q * qn, 10)) if q_i * qn_i > 1 else shown
            rows.append({
                "index": row["index"], "q": q_i, "q_next": qn_i,
                "verdicts": verdicts,
                "primitive_error_significant_digits_published": shown,
                "primitive_error_significant_digits_correct": correct,
                "predicted_from_cancellation": round(predicted, 1),
                "prediction_error": round(correct - predicted, 1),
                "capacity_fields_fully_correct": all(
                    verdicts[k] != "OVER-PUBLISHED"
                    for k in ("first_order_height_capacity",
                              "second_order_height_capacity_diagnostic")),
            })
            # the prediction must be conservative and close; if it ran ahead of
            # the measurement the mechanism claimed here is the wrong one
            if not (-0.5 <= correct - predicted <= 4.0):
                mispredicted.append(row["index"])
            if worst is None or correct < worst:
                worst = correct

    bad = [r["index"] for r in rows if any(v == "WRONG" for v in r["verdicts"].values())]
    over = [r["index"] for r in rows
            if any(v == "OVER-PUBLISHED" for v in r["verdicts"].values())]
    over_fields = sorted({k for r in rows for k, v in r["verdicts"].items()
                          if v == "OVER-PUBLISHED"})
    return {
        "rows": rows,
        "fewest_significant_digits_correct": worst,
        "rows_with_a_wrong_value": bad,
        "rows_over_published": over,
        "fields_ever_over_published": over_fields,
        "capacity_fields_over_published_anywhere":
            any(f != "primitive_error" for f in over_fields),
        "rows_where_the_cancellation_model_mispredicts": mispredicted,
    }


# ---------------------------------------------------------------------------
# section 6 — the two second-order expansion coefficients
# ---------------------------------------------------------------------------

def check_expansion_coefficients() -> dict:
    """Section 9 and section 16, tested where a wrong SECOND coefficient shows.

    Both are asymptotic expansions. Checking the constants only tests the symbols;
    the scaled residual tests the expansion. It goes to zero when the coefficient
    is right and to a nonzero constant when it is not, so the same probe both
    confirms the round's value and would reject a neighbouring one.
    """
    with mp.workdps(WORKING_DPS):
        ln2 = mp.log(2)
        eta = 1 / (6 * ln2)
        kappa = 1 / (12 * mp.sqrt(2))
        c0, c1 = ln2 / eta, ln2 * kappa / eta ** 2

        # --- section 9: ln2/(eta q - kappa sqrt q)  ==  c0/q + c1/q^{3/2} + O(q^-2)
        def residual9(q, second):
            q = mp.mpf(q)
            exact = ln2 / (eta * q - kappa * mp.sqrt(q))
            claimed = c0 / q + second / q ** mp.mpf("1.5")
            return (exact - claimed) * q ** mp.mpf("1.5")

        s9 = [{"q": "1e%d" % k,
               "residual_with_the_round_s_c1": mp.nstr(residual9(mp.mpf(10) ** k, c1), 6),
               "residual_with_c1_wrong_by_1pct":
                   mp.nstr(residual9(mp.mpf(10) ** k, c1 * mp.mpf("1.01")), 6)}
              for k in (4, 6, 8, 10, 12)]
        r_right9 = abs(residual9(mp.mpf(10) ** 12, c1))
        r_wrong9 = abs(residual9(mp.mpf(10) ** 12, c1 * mp.mpf("1.01")))

        # --- section 16: q >= A/eta + (kappa/eta^{3/2}) sqrt A + o(sqrt A)
        coeff16 = kappa / eta ** mp.mpf("1.5")

        def residual16(A, second):
            A = mp.mpf(A)
            x = (kappa + mp.sqrt(kappa ** 2 + 4 * eta * A)) / (2 * eta)
            return (x ** 2 - A / eta - second * mp.sqrt(A)) / mp.sqrt(A)

        s16 = [{"A": "1e%d" % k,
                "residual_with_the_round_s_coefficient":
                    mp.nstr(residual16(mp.mpf(10) ** k, coeff16), 6),
                "residual_with_it_wrong_by_1pct":
                    mp.nstr(residual16(mp.mpf(10) ** k, coeff16 * mp.mpf("1.01")), 6)}
               for k in (4, 6, 8, 10, 12)]
        r_right16 = abs(residual16(mp.mpf(10) ** 12, coeff16))
        r_wrong16 = abs(residual16(mp.mpf(10) ** 12, coeff16 * mp.mpf("1.01")))

        # the quadratic root the section-16 expansion approximates, checked exactly
        A = mp.mpf(10) ** 9
        x = (kappa + mp.sqrt(kappa ** 2 + 4 * eta * A)) / (2 * eta)
        root_ok = abs(eta * x ** 2 - kappa * x - A) < mp.mpf(10) ** (-WORKING_DPS + 30)

        near9 = abs(residual9(mp.mpf(10) ** 4, c1))
        near16 = abs(residual16(mp.mpf(10) ** 4, coeff16))
        near9w = abs(residual9(mp.mpf(10) ** 4, c1 * mp.mpf("1.01")))
        near16w = abs(residual16(mp.mpf(10) ** 4, coeff16 * mp.mpf("1.01")))

    return {
        "section_9_residual_falls_by_at_least_1000x_from_1e4_to_1e12":
            bool(r_right9 * 1000 < near9),
        "section_16_residual_falls_by_at_least_1000x_from_1e4_to_1e12":
            bool(r_right16 * 1000 < near16),
        "section_9_wrong_coefficient_does_not_vanish":
            bool(r_wrong9 > near9w / 2),
        "section_16_wrong_coefficient_does_not_vanish":
            bool(r_wrong16 > near16w / 2),
        "section_9_scaled_residuals": s9,
        "section_16_scaled_residuals": s16,
        "section_9_residual_at_1e12": {"round_s_value": mp.nstr(r_right9, 6),
                                       "off_by_1pct": mp.nstr(r_wrong9, 6)},
        "section_16_residual_at_1e12": {"round_s_value": mp.nstr(r_right16, 6),
                                        "off_by_1pct": mp.nstr(r_wrong16, 6)},
        "section_9_coefficient_is_discriminated": bool(r_right9 < r_wrong9 / 100),
        "section_16_coefficient_is_discriminated": bool(r_right16 < r_wrong16 / 100),
        "the_quadratic_root_solves_its_equation": bool(root_ok),
        "section_16_coefficient": mp.nstr(coeff16, 16),
    }


# ---------------------------------------------------------------------------
# section 7 — the elementary inequalities the derivation leans on
# ---------------------------------------------------------------------------

def check_inequalities() -> dict:
    with mp.workdps(60):
        ln2 = mp.log(2)
        rng = random.Random(20260823)

        # 2^D - 1 >= (ln 2) D  for D >= 0, used at section 4
        a_fail, a_tight = 0, 0
        for _ in range(4000):
            D = mp.mpf(rng.random()) * 4
            if 2 ** D - 1 < ln2 * D - mp.mpf(10) ** -40:
                a_fail += 1
            if abs(2 ** D - 1 - ln2 * D) < mp.mpf("1e-3"):
                a_tight += 1
        equality_at_zero = abs(2 ** mp.mpf(0) - 1 - ln2 * 0) < mp.mpf(10) ** -50

        # 2^{gd} - 1 >= g (2^d - 1)  for integer g >= 1, d > 0, used at section 7
        b_fail, b_equal = 0, 0
        for _ in range(4000):
            g = rng.randint(1, 40)
            d = mp.mpf(rng.random()) * 2 + mp.mpf("1e-9")
            lhs, rhs = 2 ** (g * d) - 1, g * (2 ** d - 1)
            if lhs < rhs - mp.mpf(10) ** -40:
                b_fail += 1
            if g == 1 and abs(lhs - rhs) < mp.mpf(10) ** -50:
                b_equal += 1

        # Q alpha - L = alpha D given Q = beta L + D and alpha beta = 1  (section 3)
        beta = mp.log(3, 2)
        alpha = 1 / beta
        c_fail = 0
        for _ in range(2000):
            L = mp.mpf(rng.randint(1, 10 ** 6))
            D = mp.mpf(rng.random())
            Q = beta * L + D
            if abs((Q * alpha - L) - alpha * D) > mp.mpf(10) ** -40:
                c_fail += 1

        # D <= log2(1 + L/(3y)) < 1 when L < y  (section 3)
        d_fail, d_max = 0, mp.mpf(0)
        for _ in range(2000):
            y = mp.mpf(rng.randint(3, 10 ** 9))
            L = mp.mpf(rng.randint(1, int(y) - 1))
            cap = mp.log(1 + L / (3 * y), 2)
            d_max = max(d_max, cap)
            if cap >= 1:
                d_fail += 1

    return {
        "2^D - 1 >= (ln2) D": {"samples": 4000, "violations": a_fail,
                               "samples_within_1e-3_of_equality": a_tight,
                               "equality_at_D=0": bool(equality_at_zero)},
        "2^(gd) - 1 >= g (2^d - 1)": {"samples": 4000, "violations": b_fail,
                                      "exact_equalities_at_g=1": b_equal},
        "Q alpha - L == alpha D": {"samples": 2000, "violations": c_fail},
        "D < 1 whenever L < y": {"samples": 2000, "violations": d_fail,
                                 "largest_cap_seen": mp.nstr(d_max, 8),
                                 "log2(4/3)": mp.nstr(mp.log(mp.mpf(4) / 3, 2), 8)},
        "violations": a_fail + b_fail + c_fail + d_fail,
    }


# ---------------------------------------------------------------------------
# section 8 — the renewal geometry: sparsity exponent and interval colouring
# ---------------------------------------------------------------------------

def check_renewal_geometry(theta: Fraction, sigma: Fraction) -> dict:
    with mp.workdps(60):
        th = mp.mpf(theta.numerator) / theta.denominator

        # sum_{j<=R} (2j+1)^theta  >=  ((2R+1)^{1+theta} - 1) / (2(1+theta))
        integral_fail, ratios = 0, []
        total = mp.mpf(0)
        for R in range(1, 3001):
            total += (2 * R + 1) ** th
            bound = ((2 * R + 1) ** (1 + th) - 1) / (2 * (1 + th))
            if total < bound:
                integral_fail += 1
            if R in (100, 500, 1000, 2000, 3000):
                ratios.append({"R": R, "sum_over_R^(1+theta)":
                               mp.nstr(total / R ** (1 + th), 10)})
        limit = 2 ** th / (1 + th)

        # the exponent identity the sparsity theorem turns on, exactly
        exponent_identity = (sigma * (1 + theta) == 1)
        # N >= c R^{1+theta}  =>  R <= (N/c)^sigma, as an exponent statement
        exponent_transfer = (Fraction(1) / (1 + theta) == sigma)

    # interval colouring: an interval family splits into (max overlap) disjoint
    # families, which is what section 15 uses. Checked in both directions.
    rng = random.Random(4711)
    colour_rows, colour_bad, witnessed = [], 0, 0
    overlaps_seen = set()
    for trial in range(300):
        n = rng.randint(2, 40)
        ivs = []
        for _ in range(n):
            s = rng.randint(0, 200)
            ivs.append((s, s + rng.randint(1, 60)))
        # max overlap
        events = sorted([(s, 1) for s, _ in ivs] + [(e, -1) for _, e in ivs],
                        key=lambda t: (t[0], t[1]))
        cur = omega = 0
        for _, delta in events:
            cur += delta
            omega = max(omega, cur)
        # greedy sweep colouring by left endpoint
        free, used, active = [], 0, []
        for s, e in sorted(ivs):
            active = [(end, col) for end, col in active if end > s]
            taken = {col for _, col in active}
            col = next((c for c in range(used + 1) if c not in taken), used)
            used = max(used, col + 1)
            active.append((e, col))
        overlaps_seen.add(omega)
        if used != omega:
            colour_bad += 1
        if omega >= 2:
            witnessed += 1
        if trial < 5:
            colour_rows.append({"intervals": n, "max_overlap": omega,
                                "colours_greedy_used": used})
    return {
        "sum_bound_failures": integral_fail,
        "sum_over_R^(1+theta)": ratios,
        "predicted_limit_2^theta/(1+theta)": mp.nstr(limit, 10),
        "sigma*(1+theta) == 1 exactly": bool(exponent_identity),
        "sigma == 1/(1+theta) exactly": bool(exponent_transfer),
        "colouring_trials": 300,
        "trials_where_colours_used_exceeded_max_overlap": colour_bad,
        "trials_with_a_genuine_overlap": witnessed,
        "distinct_max_overlaps_seen": len(overlaps_seen),
        "examples": colour_rows,
    }


# ---------------------------------------------------------------------------
# section 9 — is the JSON what the shipped script would produce?
# ---------------------------------------------------------------------------

def check_artifact_provenance(bundle: pathlib.Path, data: dict) -> dict:
    source = (bundle / VERIFY_SCRIPT).read_text(encoding="utf-8")
    body = source[source.index("data = {"):]
    top = re.findall(r'"([A-Za-z_0-9]+)":', body[:body.index("}")])
    row_src = source[source.index("upper_rows.append({"):]
    row_keys = re.findall(r'"([A-Za-z_0-9]+)":', row_src[:row_src.index("})")])

    json_top = list(data.keys())
    json_rows = list(data["upper_convergent_diagnostics"][0].keys())
    missing_top = [k for k in top if k not in json_top]
    extra_top = [k for k in json_top if k not in top]
    missing_row = [k for k in row_keys if k not in json_rows]
    extra_row = [k for k in json_rows if k not in row_keys]
    return {
        "script_top_level_keys": top,
        "json_top_level_keys": json_top,
        "script_row_keys": row_keys,
        "json_row_keys": json_rows,
        "top_level_keys_in_script_but_not_json": missing_top,
        "top_level_keys_in_json_but_not_script": extra_top,
        "row_keys_in_script_but_not_json": missing_row,
        "row_keys_in_json_but_not_script": extra_row,
        "json_was_produced_by_this_script":
            not (missing_top or extra_top or missing_row or extra_row),
    }


# ---------------------------------------------------------------------------

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--bundle", required=True, type=pathlib.Path)
    ap.add_argument("--cf-budget", type=float, default=60.0,
                    help="seconds to spend certifying partial quotients by "
                         "integer comparison before falling back")
    ap.add_argument("--out", type=pathlib.Path)
    args = ap.parse_args()

    bundle = args.bundle
    data = json.loads((bundle / CONSTANTS_JSON).read_text(encoding="utf-8"))
    doc = (bundle / ROUND_DOC).read_text(encoding="utf-8")

    rho = Fraction(data["rho_star"])
    theta = 1 / (rho + 1)
    sigma = 1 / (1 + theta)

    rep = {
        "round": "Hard-Zeta Phase II / Round A-U.2d.3",
        "source_item": 47,
        "exponent_chain": check_exponent_chain(data),
        "transcendental_constants": check_transcendental_constants(data, doc),
    }
    rep["continued_fraction"] = check_continued_fraction(data, args.cf_budget)
    rep["cf_tax"] = check_cf_tax(data, rep["continued_fraction"])
    rep["upper_convergent_filter"] = check_upper_filter(data, rep["continued_fraction"])
    rep["shipped_rows"] = check_row_arithmetic(data)
    rep["expansion_coefficients"] = check_expansion_coefficients()
    rep["elementary_inequalities"] = check_inequalities()
    rep["renewal_geometry"] = check_renewal_geometry(theta, sigma)
    rep["artifact_provenance"] = check_artifact_provenance(bundle, data)

    ec = rep["exponent_chain"]
    tc = rep["transcendental_constants"]
    cf = rep["continued_fraction"]
    tax = rep["cf_tax"]
    filt = rep["upper_convergent_filter"]
    sr = rep["shipped_rows"]
    xc = rep["expansion_coefficients"]
    ineq = rep["elementary_inequalities"]
    rg = rep["renewal_geometry"]
    ap_ = rep["artifact_provenance"]

    failures = []
    if not ec["identities"]["rho_star is conservative against the cited exponent"]:
        failures.append("rho_star is not conservative against the exponent the "
                        "round cites")
    if not ec["all_identities_hold"]:
        failures.append("the exponent chain does not satisfy its own identities")
    if ec["wrong_digits"]:
        failures.append("published exponent digits are wrong: %s" % ec["wrong_digits"])
    if not tc["all_relations_hold"]:
        failures.append("the constants contradict each other")
    if tc["disagreeing_beyond_rounding"]:
        failures.append("a published constant disagrees with its closed form far "
                        "beyond rounding: %s" % tc["disagreeing_beyond_rounding"])
    if tc["document_constants_disagreeing"]:
        failures.append("round-document constants disagree: %s"
                        % tc["document_constants_disagreeing"])
    if cf["disagreements"]:
        failures.append("recomputed continued fraction disagrees with the JSON")
    if not cf["the_two_methods_agree_everywhere_both_ran"]:
        failures.append("the integer and high-precision routes disagree")
    if cf["terms_certified_by_integer_comparison"] < 12:
        failures.append("too few partial quotients certified to be worth reporting")
    if not cf["cmp_pow_self_test"]["all_correct"]:
        failures.append("the integer comparison primitive is wrong on cases "
                        "decided by hand")
    if cf["integer_comparisons_performed"] < 25:
        failures.append("the certified route did not perform integer comparisons, "
                        "so its independence from the artifact's method is a claim "
                        "rather than a measurement")
    if tax["rows_decided_exactly"] < 5:
        failures.append("the exact bracket decided too few rows to be the primary "
                        "route")
    if not tax["every_row_holds_by_one_route_or_the_other"]:
        failures.append("the continued-fraction tax inequality is violated")
    if not filt["the_filter_is_right_in_both_directions"]:
        failures.append("the upper-convergent filter is wrong in one direction")
    if sr["rows_with_a_wrong_value"]:
        failures.append("a shipped row value is wrong, not merely over-published")
    if sr["rows_where_the_cancellation_model_mispredicts"]:
        failures.append("the cancellation model does not predict the observed "
                        "digit loss at rows %s"
                        % sr["rows_where_the_cancellation_model_mispredicts"])
    if not xc["section_9_coefficient_is_discriminated"]:
        failures.append("the section-9 residual does not discriminate its coefficient")
    if not xc["section_16_coefficient_is_discriminated"]:
        failures.append("the section-16 residual does not discriminate its coefficient")
    if not (xc["section_9_residual_falls_by_at_least_1000x_from_1e4_to_1e12"]
            and xc["section_9_wrong_coefficient_does_not_vanish"]):
        failures.append("the section-9 residual does not discriminate its "
                        "coefficient asymptotically")
    if not (xc["section_16_residual_falls_by_at_least_1000x_from_1e4_to_1e12"]
            and xc["section_16_wrong_coefficient_does_not_vanish"]):
        failures.append("the section-16 residual does not discriminate its "
                        "coefficient asymptotically")
    if not xc["the_quadratic_root_solves_its_equation"]:
        failures.append("the section-16 quadratic root is wrong")
    if ineq["violations"]:
        failures.append("an elementary inequality the derivation uses fails")
    if rg["sum_bound_failures"] or rg["trials_where_colours_used_exceeded_max_overlap"]:
        failures.append("the renewal geometry does not hold as stated")
    if not (rg["sigma*(1+theta) == 1 exactly"] and rg["sigma == 1/(1+theta) exactly"]):
        failures.append("the sparsity exponent identity fails")
    if rg["distinct_max_overlaps_seen"] < 3 or rg["trials_with_a_genuine_overlap"] < 50:
        failures.append("the colouring sample never exercised a real overlap")

    findings = []
    if tc["over_published"]:
        findings.append(
            "the constants JSON over-publishes its own precision: %s %s a final "
            "digit the 100-digit computation behind it does not support, out of "
            "%d transcendental constants checked. Same class as item 45 (RUN-027), "
            "second occurrence and far milder. The three exponent figures are "
            "exactly rational and are right to every published digit."
            % (", ".join(tc["over_published"]),
               "carries" if len(tc["over_published"]) == 1 else "carry",
               len(tc["published_digits"])))
    if sr["rows_over_published"]:
        findings.append(
            "the per-row `primitive_error` is published to %d significant digits at "
            "every convergent while the computation behind it supports between %d "
            "and %d, and the shortfall is exactly the cancellation in `p - beta*q`: "
            "predicted by `log10(beta*q*q+)` to within %.1f digits at every row, "
            "always conservatively. The two capacity fields are unaffected: %s."
            % (sr["rows"][0]["primitive_error_significant_digits_published"],
               sr["fewest_significant_digits_correct"],
               max(r["primitive_error_significant_digits_correct"] for r in sr["rows"]),
               max(abs(r["prediction_error"]) for r in sr["rows"]),
               "none is over-published"
               if not sr["capacity_fields_over_published_anywhere"]
               else "they are too"))
    if not ap_["json_was_produced_by_this_script"]:
        findings.append("the shipped JSON is not what the shipped script produces")

    rep["findings"] = findings
    rep["failures"] = failures
    rep["passed"] = not failures

    text = json.dumps(rep, indent=2, ensure_ascii=False)
    if args.out:
        args.out.write_text(text + "\n", encoding="utf-8")
    print(text)
    return 0 if rep["passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
