#!/usr/bin/env python3
import json
from pathlib import Path

u = [[1, 1], [0, 1]]
A = [[u[0][0]-1, u[0][1]], [u[1][0], u[1][1]-1]]
det = u[0][0]*u[1][1] - u[0][1]*u[1][0]
assert det == 1
assert A == [[0, 1], [0, 0]]
# Image(A) is generated by the primitive vector e1, so Z_p^2/Image(A) is free rank one.
primitive_generator = (1, 0)
assert primitive_generator == (1, 0)
result = {
    "matrix_u": u,
    "determinant": det,
    "u_minus_1": A,
    "image_generator": list(primitive_generator),
    "quotient_free_rank": 1,
    "quotient_torsion": 0,
    "condition_im_linear_algebra": "PASS"
}
path = Path(__file__).resolve().parents[1] / "results" / "condition_im_replay.json"
path.write_text(json.dumps(result, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
print("CONDITION_IM_REPLAY_OK")
