#!/usr/bin/env python3
import json
from math import gcd
from pathlib import Path

A = -3024
B = 46224
P = (12, 108)   # image of (0,0)
Q = (48, 108)   # image of (1,0)
PRIMES = {
    397: {"expected_order": 374, "cofactor_11": 34, "expected_dlog_Q_in_P": 244, "expected_slope": 2},
    991: {"expected_order": 1045, "cofactor_11": 95, "expected_dlog_Q_in_P": 356, "expected_slope": 4},
}

def inv(a, p):
    return pow(a % p, -1, p)

def add(R, S, p):
    if R is None:
        return S
    if S is None:
        return R
    x1, y1 = R
    x2, y2 = S
    if x1 == x2 and (y1 + y2) % p == 0:
        return None
    if R == S:
        if y1 % p == 0:
            return None
        lam = ((3 * x1 * x1 + A) * inv(2 * y1, p)) % p
    else:
        lam = ((y2 - y1) * inv(x2 - x1, p)) % p
    x3 = (lam * lam - x1 - x2) % p
    y3 = (lam * (x1 - x3) - y1) % p
    return (x3, y3)

def mul(n, R, p):
    T = None
    S = R
    while n:
        if n & 1:
            T = add(T, S, p)
        S = add(S, S, p)
        n >>= 1
    return T

def point_order(R, p, bound):
    T = None
    for k in range(1, bound + 1):
        T = add(T, R, p)
        if T is None:
            return k
    raise RuntimeError("order bound exceeded")

def legendre(a, p):
    a %= p
    if a == 0:
        return 0
    t = pow(a, (p - 1) // 2, p)
    return -1 if t == p - 1 else t

def count_points(p):
    # Short model Y^2 = X^3 + A X + B.
    total = 1
    for x in range(p):
        total += 1 + legendre(x*x*x + A*x + B, p)
    return total

def discrete_log_bruteforce(base, target, p, order):
    R = None
    for k in range(order):
        if R == target:
            return k
        R = add(R, base, p)
    raise RuntimeError("discrete log not found")

def local_slope(base11, target11, p):
    R = None
    for k in range(11):
        if R == target11:
            return k
        R = add(R, base11, p)
    raise RuntimeError("local slope not found")

result = {
    "schema_version": "1.1",
    "curve": "389.a1",
    "prime": 11,
    "short_model": {"A": A, "B": B, "P": list(P), "Q": list(Q)},
    "local": {},
}

for ell, meta in PRIMES.items():
    orderE = count_points(ell)
    assert orderE == meta["expected_order"]
    Pord = point_order(P, ell, orderE)
    Qord = point_order(Q, ell, orderE)
    dlog = discrete_log_bruteforce(P, Q, ell, orderE)
    assert Pord == orderE
    assert dlog == meta["expected_dlog_Q_in_P"]
    m = meta["cofactor_11"]
    mP = mul(m, P, ell)
    mQ = mul(m, Q, ell)
    assert mP is not None and mul(11, mP, ell) is None
    assert mQ is not None and mul(11, mQ, ell) is None
    slope = local_slope(mP, mQ, ell)
    assert slope == meta["expected_slope"]
    result["local"][str(ell)] = {
        "point_count": orderE,
        "v11_point_count": 1,
        "P_order": Pord,
        "Q_order": Qord,
        "Q_discrete_log_base_P": dlog,
        "cofactor_to_11_primary": m,
        "mP": list(mP),
        "mQ": list(mQ),
        "norm_quotient_slope_Q_over_P": slope,
        "norm_quotient_dimension_F11": 1,
    }

M = [[1, result["local"]["397"]["norm_quotient_slope_Q_over_P"]],
     [1, result["local"]["991"]["norm_quotient_slope_Q_over_P"]]]
det_mod_11 = (M[0][0]*M[1][1] - M[0][1]*M[1][0]) % 11
assert M == [[1,2],[1,4]]
assert det_mod_11 == 2

# Full simultaneous reduction map in cyclic coordinates generated by P.
# (a,b) maps to (a+244b mod 374, a+356b mod 1045).
# These two vectors are in the kernel.
v1 = (5742, -22)
v2 = (-254980, 1045)
for a,b in (v1,v2):
    assert (a + 244*b) % 374 == 0
    assert (a + 356*b) % 1045 == 0
kernel_basis_det = abs(v1[0]*v2[1] - v1[1]*v2[0])
target_order = 374 * 1045
assert kernel_basis_det == target_order == 390830

# Direct CRT compatibility proof of surjectivity: gcd moduli = 11 and
# (356-244)=112 is invertible mod 11, so b can match every compatibility class.
g = gcd(374,1045)
diff = (356 - 244) % g
assert g == 11
assert gcd(diff, g) == 1

result["localization_matrix_mod11"] = M
result["localization_det_mod11"] = det_mod_11
result["mw_mod11_to_two_norm_quotients"] = "ISOMORPHISM"
result["full_reduction"] = {
    "cyclic_coordinates": {
        "397": "a + 244*b mod 374",
        "991": "a + 356*b mod 1045"
    },
    "kernel_basis": [list(v1), list(v2)],
    "kernel_basis_determinant": kernel_basis_det,
    "target_order": target_order,
    "gcd_moduli": g,
    "dlog_difference_mod_gcd": diff,
    "surjective": True,
    "cokernel_order_J_S": 1,
    "index_E_over_E_S": target_order,
    "v11_index_E_over_E_S": 2,
}
result["status"] = {
    "anomalous_collision": "CLOSED_EXACT",
    "local_norm_localization": "CLOSED_EXACT",
    "full_reduction_surjectivity": "CLOSED_EXACT",
    "classical_nonanomalous_MT_height_backend": "NOT_APPLICABLE_TO_THESE_RAMIFIED_PRIMES",
    "anomalous_bockstein_comparison": "OPEN"
}

out = Path(__file__).resolve().parents[1] / "results" / "anomalous_norm_localization_certificate.json"
out.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
print("ANOMALOUS_NORM_LOCALIZATION_EXACT")
print("M_loc =", M)
print("det(M_loc) mod 11 =", det_mod_11)
print("J_S = 1")
print("[E(Q):E^S(Q)] =", target_order)
